<a href="https://colab.research.google.com/github/alejandra199961-cell/Bono_N-mero_1_Estad-stica_2_Alejandra_Bueno_2221974.ipynb/blob/main/Bono_N%C3%BAmero_1_Estad%C3%ADstica_2_Alejandra_Bueno_2221974.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Nombre:** María Alejandra Bueno León

**Código.** 2221974

**Curso:** Estadística 2

**Grupo:** A1

**Profesor:** Andrés Sebástian Ríos Gutiérrez

**Pregrado:** Licenciatura en Matemáticas

**Modalidad:** Presencial

Manejo de módulos integrados

NumPy: se usa principalmente para trabajar con datos númericos de forma rápida, eficiente y estructurada. Un objeto tipo NumPy es un arreglo base para hacer matemáticas y manipular datos en Phyton.

Pandas: se usa para trabajar con datos estructurales (Como tablas de Excel o bases de datos). Un objeto tipo pandas permite cargar, limpiar, transformar y analizar datos. Lo usamos para bases de datos relacionales.

La diferencia entre NumPy y Pandas radica en su propósito y nivel de uso: NumPy es una liberia enfocada en el cálculo numérico eficiente mediante arrays multidimensionales, ideal para operaciones matemáticas rápidas, álgebra lineal y procesamiento de datos puramente numéricos; mientras que Pandas es una libreria de más alto nivel diseñada para la manipulación y análisis de datos estructurados, como tablas tipo Excel o bases de datos, permitiendo trabajar con columnas con nombres, datos de distintos tipos, limpieza, filtrado y agrupación; en la práctica, Pandas se apoya internamente de NumPy, por lo que ambos se complementan y se utilizan juntos en la mayoria de flujos de ciencia de datos.



# NumPy (Numerical Python)

Es la biblioteca fundamental para el cómputo científico en Python. Su fuerte es el manejo de arreglos multidimensionales (matrices) y el cálculo matemático de alta velocidad.

* **Uso en Ciencia de Datos:** Se utiliza en las capas más bajas de los algoritmos. Es la herramienta para realizar operaciones de álgebra lineal, transformaciones matriciales, generación de números aleatorios y operaciones matemáticas complejas sobre grandes volúmenes de datos numéricos.

### Ventajas para implementar algoritmos

* **Velocidad y eficiencia (Vectorización):** Los arreglos de NumPy (`ndarrays`) están escritos en C. Ejecutan operaciones en bloques de datos completos sin necesidad de usar bucles `for` en Python, lo que acelera masivamente el entrenamiento de algoritmos.
* **Eficiencia en memoria:** Almacena los datos en bloques contiguos de memoria y exige que todos los elementos sean del mismo tipo, lo que reduce drásticamente el espacio que ocupa en comparación con las listas nativas de Python.
* **Álgebra lineal nativa:** Viene con módulos específicos (`numpy.linalg`) indispensables para resolver sistemas de ecuaciones, calcular autovalores o descomponer matrices, la base de algoritmos como la Regresión Lineal o PCA (Análisis de Componentes Principales).

### Desventajas para implementar algoritmos

* **Rigidez de tipos (Homogeneidad):** Un arreglo de NumPy solo puede contener un tipo de datos a la vez (por ejemplo, solo flotantes). Si intentas mezclar texto y números, NumPy convertirá todo a cadenas, perdiendo la capacidad de hacer cálculos.
* **Estructura estática:** No maneja bien la inserción o eliminación de columnas o filas sobre la marcha; cambiar el tamaño de un arreglo suele implicar recrearlo por completo en memoria.
* **Falta de etiquetas:** Los datos se indexan estrictamente por su posición numérica (0, 1, 2...). No puedes nombrar las columnas, lo que dificulta trabajar con datos tabulares complejos.

---

# Pandas (Python Data Analysis Library)

Es la biblioteca estándar para la manipulación y el análisis de datos tabulares (estructurados en filas y columnas). Está construida directamente sobre NumPy.

* **Uso en Ciencia de Datos:** Domina las etapas de **limpieza, preparación y exploración de datos (EDA)**. Se usa para cargar archivos (CSV, Excel, SQL), manejar datos faltantes, filtrar, agrupar y transformar variables antes de pasarlas a un modelo de Machine Learning.

### Ventajas para implementar algoritmos

* **Estructuras heterogéneas (`DataFrames`):** Permite mezclar diferentes tipos de datos (columnas con texto, columnas con números, fechas, booleanos) en una sola tabla, reflejando fielmente las bases de datos de la vida real.
* **Indexación por etiquetas:** Puedes acceder a los datos usando los nombres reales de las variables o textos en las filas, haciendo que el código del algoritmo sea mucho más intuitivo y fácil de depurar.
* **Herramientas avanzadas de alineación y limpieza:** Facilita enormemente el manejo de valores nulos o faltantes (`NaN`), la fusión de tablas (`merge`, `join`) y la agrupación de datos (`groupby`), tareas que toman el 80% del tiempo antes de correr un algoritmo.

### Desventajas para implementar algoritmos

* **Alto consumo de memoria:** Pandas duplica o triplica fácilmente el tamaño del archivo original en la memoria RAM debido a los metadatos y los índices que genera para facilitar la búsqueda. No está optimizado para Big Data en una sola máquina.
* **Menor rendimiento en cálculo puro:** Aunque usa NumPy por debajo, añadir capas de abstracción (como las etiquetas de texto) hace que las operaciones matemáticas puras sean notablemente más lentas en Pandas que si se hicieran directamente en NumPy.
* **Sintaxis compleja y redundante:** Existen muchas formas de hacer una misma tarea (por ejemplo, filtrar filas), lo que puede dar lugar a errores sutiles como las advertencias de copia (`SettingWithCopyWarning`) si no se tiene cuidado al modificar datos dentro del algoritmo.

Carga de Paquete np de NumPy:

In [1]:
import numpy as np

Creando arreglos:

In [2]:
a = np.array([6, 7, 8, 9])
b = np.array([[6, 7], [8, 9]])
print(a)
print(b)

[6 7 8 9]
[[6 7]
 [8 9]]

In [3]:
a = np.array([6, 7, 8, 9])
b = np.array([[6, 7], [8, 9], [6, 7]])
print(a)
print(b)

[6 7 8 9]
[[6 7]
 [8 9]
 [6 7]]

In [4]:
b*2 #Toma la matriz y está multiplicando cada elemento dentro de la matriz por 2

array([[12, 14],
       [16, 18],
       [12, 14]])

In [10]:
lista = [4, 5, 6] #Objetos que no son inmutables, es decir, se pueden intercambiar los elementos dentro de una lista y podemos indemzar cada elemento de la lista
arr = np.array([7, 8, 9])

In [11]:
lista*2 #Lista concatenada, es decir, voy a tener la lista obtenida antes 2 veces escrita

[4, 5, 6, 4, 5, 6]

In [12]:
arr*2 #Hay una interpretación de los arreglos tipo numpy más apegados a lo que vemos de los #obejtos matemáticos como los vectores

array([14, 16, 18])

In [13]:
arr.shape #Forma (Dimensiones)

(3,)

In [14]:
b.shape #Arreglo de tres componentes cada uno con dos elementos

(3, 2)

In [15]:
arr.ndim #Número de dimensiones

1

In [16]:
b.ndim #Número de elementos por cada componente

2

In [17]:
b.dtype #Tipo de dato

dtype('int64')

In [18]:
b.size #Cantidad de elementos en todas las componentes

6

Arreglos especiales:

In [19]:
np.zeros((3,4)) #Todo lleno de ceros: 3 componentes y 4 elementos por componente - Arreglo de ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((4,4)) #Todo lleno de ceros: 2 componentes y 4 elementos por componente - Arreglo de unos

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.eye(4) #La matriz identidad de una matriz cuadrada de tamaño 4 - Arreglo de la matriz identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.arange(0, 20,3) #Del 0 hasta el 20 (sin tomar el 20), separado por 3

array([ 0,  3,  6,  9, 12, 15, 18])

In [27]:
np.linspace(0,3,5) #5 elementos equidistantes entre el 0 y el 1

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

In [29]:
arry = np.array([5, 10, 15, 20]) #Llamar la función del módulo
arry[0]

np.int64(5)

In [30]:
arry[-1]

np.int64(20)

In [32]:
arry[1:3] #Tomando de índice del 1 al 3 (sin tomar el 3)

array([10, 15])

Indexación de matrices:

Matri= (4 5 6
        7 8 9) y es nuestro objeto matemático
        
        Matri[0,1]=5

        Matri[:,1]=(5,8)

        Matri[1,:]=(7,8,9)

In [33]:
matri = np.array([[4,5,6],[7,8,9]]) #Definición de Matriz

In [36]:
matri[0,1] #El índice 1 de la ceroésima fila - Elemento 0,1

np.int64(5)

In [37]:
matri[:,1]

array([5, 8])

In [38]:
matri[:,0] #

array([4, 7])

In [39]:
matri[1,:]

array([7, 8, 9])

In [40]:
a = np.array([4, 5, 6])
b = np.array([7, 8, 9])
a + b
#Sumar componente a componente

array([11, 13, 15])

In [41]:
a*b
#Multiplicar componente a componente
#Producto de Hadamard entre dos arreglos (vectores)

array([28, 40, 54])

In [42]:
matri1 = np.array([[2,4,6],[8,10,12]]) #Definición de Matriz 1
matri1*matri #Producto de Hadamard es decir producto componente a componente

array([[  8,  20,  36],
       [ 56,  80, 108]])

In [43]:
[x * 2 for x in lista] #Lento

[8, 10, 12]

In [44]:
arr * 2 #Rápido

array([14, 16, 18])

Funciones Estadísticas implementadas:

In [46]:
c=np.array([1.63, 1.59, 1.80, 1.75, 1.55, 1.86, 1.72])
print(np.mean(c), np.median(c), np.std(c), np.sum(c), np.min(c), np.max(c))
#Determina la media, la mediana, la desviación estándar, el total, el valor mínimo, el valor máximo
#Entonces el valor de la mitad es 1.72, es decir que el 50% de las personas mide 1.70 cm
#La desviación estándar es de 11 cm, es decir que la distancia entre todos es el promedio con una diferencia de 11 centimetros
#La suma de todas las estaturas es de 11,9 metros
#La estatura más pequeña es de 1 metro con 55 centimetros
#La estatura más grande es de 1 metro  con 86 centimetros
#De este ejemplo se puede obtener la utilidad de NumPy, que es la construcción de métodos estadísticos, que son muy útiles
#En la Estadística descriptiva por medio de la Ciencia de Datos, por eso se utilizan elementos tipo NumPy

1.7 1.72 0.10555973258234953 11.9 1.55 1.86

Manipulación de Arreglos:

In [49]:
d = np.array([0, 2, 4, 6, 8, 10]) #Cambiar formas
d.reshape(2,3)
#Inicialmente,tien seis componentes de un elemento cada una
#El primer argumento me dice el número de componentes, cambia a dos componentes cada una con tres elementos

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [50]:
np. concatenate([d, a]) #Concatenar arreglos, es decir a un arreglo le pego otro

array([ 0,  2,  4,  6,  8, 10,  4,  5,  6])

In [51]:
np. concatenate(d.reshape(2,3))

array([ 0,  2,  4,  6,  8, 10])

In [52]:
d.reshape(2,3).flatten() #Vectoriza la matriz

array([ 0,  2,  4,  6,  8, 10])

In [53]:
a = np.array([[3, 4],[5, 6]])
b = np.array([[7, 8],[9, 10]]) #Producto punto - Multiplicación de matrices

np.dot(a, b)

array([[ 57,  64],
       [ 89, 100]])

In [54]:
np.linalg.det(a) #Determinante - Funciones de álgebra lineal y se calcula el determinante de una matriz

np.float64(-1.9999999999999971)

In [55]:
np.linalg.inv(a) #Inversa de una matriz

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

In [56]:
np.linalg.matrix_transpose(a) #Traspuesta de una matriz

array([[3, 5],
       [4, 6]])

In [62]:
np.random.rand(20) #Números aleatorios entre cero y uno
#Es decir genera 20 valores aletarorios de una distribución uniforme en el intervalo (0,1)

array([0.57227769, 0.60405628, 0.05724136, 0.56995676, 0.31704636,
       0.82501036, 0.89051326, 0.68999417, 0.48501324, 0.63536925,
       0.90234219, 0.75904897, 0.70069498, 0.32315755, 0.48013708,
       0.50893211, 0.9851498 , 0.27654324, 0.20854097, 0.37543287])

In [61]:
np.random.randint(0,15) #Genera un valor entero entre 0 y el anterior al 15
#Un valor de la distribución uniforme discreta

0

In [64]:
np.random.randn(6) #Genera 6 valores aleatorios de una distribución normal con media 0 y
#Desviación estándar 1

array([ 1.41821496, -0.35413698,  0.20655256,  1.21993187,  0.70546165,
        1.08468978])

In [65]:
e = np.array([6, 7, 8, 9, 10]) #Filtrado y condiciones
f = e[e > 3]
f

array([ 6,  7,  8,  9, 10])

In [66]:
e[(e > 3) & (e < 6)] #Note que el y es así &. El o es así |

array([], dtype=int64)

In [67]:
np.where(e > 6, 1, 0) #donde e > 3 anotamos un 1, y donde no, anotamos un 0

array([0, 1, 1, 1, 1])

In [68]:
np.where(e > 6, 1, e) #Los valores que no queremos reemplazar, anotamos el mismo objeto

array([6, 1, 1, 1, 1])

Ahora con Pandas

Importamos el paquete de Pandas

In [3]:
import pandas as pd

In [4]:
s = pd.Series([5, 15, 25]) #Vector columna
s
#Pandas es un objeto tipo tabla

0     5
1    15
2    25
dtype: int64

In [5]:
df = pd.DataFrame({ 'nombre': ['Isabel', 'Andrés', 'Kevin', 'Lucía'],
                   'ciudad': ['Cartagena', 'Bucaramanga', 'Cali', 'Pereira'],
                    'edad': [25, 32, 24, 23],
                    'salario': [2500, 3000, 1500, 2000]
                    }) #Creando data.frames y es un objeto tipo Diccionario
df

   nombre       ciudad  edad  salario
0  Isabel    Cartagena    25     2500
1  Andrés  Bucaramanga    32     3000
2   Kevin         Cali    24     1500
3   Lucía      Pereira    23     2000

In [6]:
average_salary_by_city = df.groupby('ciudad')['salario'].mean()
display(average_salary_by_city)

ciudad
Bucaramanga    3000.0
Cali           1500.0
Cartagena      2500.0
Pereira        2000.0
Name: salario, dtype: float64

In [7]:
df.head() #primeras filas
#Nos da los primeros 4 datos de nuestra base de datos

   nombre       ciudad  edad  salario
0  Isabel    Cartagena    25     2500
1  Andrés  Bucaramanga    32     3000
2   Kevin         Cali    24     1500
3   Lucía      Pereira    23     2000

In [8]:
df.tail(2) #Últimas filas
#Nos muestras las dos últimas filas de nuestra base de datos

  nombre   ciudad  edad  salario
2  Kevin     Cali    24     1500
3  Lucía  Pereira    23     2000

In [9]:
df.info() #Tipo de datos
#Nos muestra cada una de las columnas, sí hay elementos nulos, es decir, datos faltantes y el tipo de objeto
#Los primeros objetos son cadenas, pueden ser texto o pueden ser elementos de tipo buleano
#La edad son enteros y el salario son números enteros, la memoria usada es de 260 bytes
#Nos muestra que tiene 4 entradas, es decir que son de 0 a 3, esos son los individuos
#Y que tiene 4 columnas
#Lo que hace la función en general es hacer un pequeño resumen de como es nuestra base de datos y el tipo de objetos
#que tiene nuestra base de datos, en nuestro caso, nuestra data.frame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nombre   4 non-null      object
 1   ciudad   4 non-null      object
 2   edad     4 non-null      int64
 3   salario  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [10]:
df.describe() #Estadísticas
#Que hace el método describe estadísticas descriptivas básicas para variables cuantitativas
#Me cuenta cuántos datos tenemos, la media aritmética, podemos decir que en promedio la edad de las personas
#de la empresa es de 26 años, que el promedio del salario es de $2.250 dolares,
#Que hay una desviación estándar de de 4.1 años aproximadamente y una desviación estándar de $645.5 dolares,
#La edad mínima de los empleados es 23 y la edad máxima es de 32
#La desviación estándar mínima de $1.500 dolares y la desviación estándar máxima de #3.000 dolares
#Incluso calcula los cuantiles, la mediana que es el 50% que es la mitad de los empleados tiene hasta 25 años
#Y el salario de la mitad de los empleados es de $2.250 dolares
#Así es la forma de interpretar las estadísticas descriptivas

            edad      salario
count   4.000000     4.000000
mean   26.000000  2250.000000
std     4.082483   645.497224
min    23.000000  1500.000000
25%    23.750000  1875.000000
50%    24.500000  2250.000000
75%    26.750000  2625.000000
max    32.000000  3000.000000

In [11]:
df.shape #(filas, columnas)
#El método shape nos dice el número de filas y el número de columnas que tiene mi base de datos

(4, 4)

In [12]:
salario_promedio = df['salario'].mean()
print( f"El salario_promedio: {salario_promedio}")
#

El salario_promedio: 2250.0

In [13]:
df['edad'] #Para imprimir la columna edad

0    25
1    32
2    24
3    23
Name: edad, dtype: int64

In [14]:
df[['nombre', 'edad']] #Selección de columnas, utilizando una lista con los respectivos nombres

   nombre  edad
0  Isabel    25
1  Andrés    32
2   Kevin    24
3   Lucía    23

In [15]:
df[df['edad'] >25] #Selección de filas, es decir las personas que tengan más de 25 años

   nombre       ciudad  edad  salario
1  Andrés  Bucaramanga    32     3000

In [16]:
df[(df['edad'] > 18) & (df['edad']  < 35)] #Las personas que tengan más de 18 años, pero que sean menores de 35 años

   nombre       ciudad  edad  salario
0  Isabel    Cartagena    25     2500
1  Andrés  Bucaramanga    32     3000
2   Kevin         Cali    24     1500
3   Lucía      Pereira    23     2000

In [24]:
import numpy as np

data = {
    'nombre': ['Brallan', 'Mariangel', 'Jeiner', 'Alejandra', None],
        'edad': [26, np.nan, 30, 27, 24],
        'salario': [2000, 4000, None, 3000, 5000],
        'ciudad': ['Pereira', 'Cartagena', 'Bucaramanga', 'Cali', 'Bucaramanga']
    }
data

{'nombre': ['Brallan', 'Mariangel', 'Jeiner', 'Alejandra', None],
 'edad': [26, nan, 30, 27, 24],
 'salario': [2000, 4000, None, 3000, 5000],
 'ciudad': ['Pereira', 'Cartagena', 'Bucaramanga', 'Cali', 'Bucaramanga']}

In [25]:
data1 = pd.DataFrame(data) #Así tranformamos un diccionario en una tabla de Pandas
data1

      nombre  edad  salario       ciudad
0    Brallan  26.0   2000.0      Pereira
1  Mariangel   NaN   4000.0    Cartagena
2     Jeiner  30.0      NaN  Bucaramanga
3  Alejandra  27.0   3000.0         Cali
4       None  24.0   5000.0  Bucaramanga

In [26]:
data1.isnull() #Valores Faltantes
#El médoto isnull, muestra true si el valor es faltante y false si el valor no es faltante

   nombre   edad  salario  ciudad
0   False  False    False   False
1   False   True    False   False
2   False  False     True   False
3   False  False    False   False
4    True  False    False   False

In [27]:
data1.isnull().sum() #El método sum, suma los valores por columnas: 1 si es faltante, 0 si no.

nombre     1
edad       1
salario    1
ciudad     0
dtype: int64

In [28]:
data2 = data1.dropna() #El modelo Dropna, elimina las filas con valores faltantes
data2

      nombre  edad  salario   ciudad
0    Brallan  26.0   2000.0  Pereira
3  Alejandra  27.0   3000.0     Cali

In [29]:
data1.dropna(subset=['salario']) #Se eliminan las filas con valores faltantes, únicamente
#en la columna salario

      nombre  edad  salario       ciudad
0    Brallan  26.0   2000.0      Pereira
1  Mariangel   NaN   4000.0    Cartagena
3  Alejandra  27.0   3000.0         Cali
4       None  24.0   5000.0  Bucaramanga

In [30]:
data1['edad'] = data1['edad'].fillna(data1['edad'].mean())
data1['nombre'] = data1['nombre'].fillna('Desconocido')
data1
#Se están imputando datos faltantes, es decir que ponga la media aritmética de la columna de edad de data1
#Con la columna nombre la esta reemplazando con la misma columna nombre, pero a los valores faltantes les pone desconocido
#Importante. En el anáslisis de datos no nos interesa el nombre, sino calcular la edad promedio de las personas de la empresa

        nombre   edad  salario       ciudad
0      Brallan  26.00   2000.0      Pereira
1    Mariangel  26.75   4000.0    Cartagena
2       Jeiner  30.00      NaN  Bucaramanga
3    Alejandra  27.00   3000.0         Cali
4  Desconocido  24.00   5000.0  Bucaramanga

In [31]:
data1['ciudad'] = data1['ciudad'].replace('Bucaramanga', 'BUCARAMANGA')
data1
#El modelo replace o reemplazo, lo que hace es reemplazar la palabra Bucaramanga por BUCARAMANGA en Mayúscula, en la columna ciudad
#de data1

        nombre   edad  salario       ciudad
0      Brallan  26.00   2000.0      Pereira
1    Mariangel  26.75   4000.0    Cartagena
2       Jeiner  30.00      NaN  BUCARAMANGA
3    Alejandra  27.00   3000.0         Cali
4  Desconocido  24.00   5000.0  BUCARAMANGA

In [32]:
data4 = data1['ciudad'].drop_duplicates()
data4
#Se toma data1 sin duplicados

0        Pereira
1      Cartagena
2    BUCARAMANGA
3           Cali
Name: ciudad, dtype: object

In [33]:
data5 = {
    'nombre': ['Marcela', 'Angel', 'Lisseth', 'Angelmiro', 'Eugenio'],
        'edad': [36, 24, 35, 65, 70],
        'ciudad': ['Bucaramanga', 'Cali', 'Cartagena', 'Medellín', 'Bucaramanga']
    }
data5 = pd.DataFrame(data5)
data5

      nombre  edad       ciudad
0    Marcela    36  Bucaramanga
1      Angel    24         Cali
2    Lisseth    35    Cartagena
3  Angelmiro    65     Medellín
4    Eugenio    70  Bucaramanga

In [34]:
data6 = data5.drop_duplicates()
data6
#Aquellos valores que tengang duplicados, pues no los considera

      nombre  edad       ciudad
0    Marcela    36  Bucaramanga
1      Angel    24         Cali
2    Lisseth    35    Cartagena
3  Angelmiro    65     Medellín
4    Eugenio    70  Bucaramanga

In [42]:
dfn = pd.DataFrame({
    'id': [11, 12, 13, 14],
    'nombre': ['Camila', 'CRISTHIAN', 'Juan', 'Betty'],
        'edad': [25, 32, 27, 30],
        'salario': [2000, 3000, 4000, 5000],
        'ciudad': ['Bucaramanga', 'Cartagena', 'Bucaramanga', 'Cali']
    })
dfn

   id     nombre  edad  salario       ciudad
0  11     Camila    25     2000  Bucaramanga
1  12  CRISTHIAN    32     3000    Cartagena
2  13       Juan    27     4000  Bucaramanga
3  14      Betty    30     5000         Cali

In [43]:
dfn['salario_anual'] = dfn['salario'] * 12 #aplicar función
dfn['edad_doble'] = dfn['edad'].apply(lambda x: x * 2)
dfn
#Estamos agregando una nueva columna: una que es el salario anual y la otra que es el doble de la edad
#Una ventaja de trabajar con Pandas, es la sintáxis tan fácil que tiene
#Cálculo del salario anual y es al parecer trabajador por OPS así que debe pagar su salud como pensión por aparte
#Otra ventaja es que Pandas también entiende la sintaxis que ingeniamos para listas, por eso aplica la función lambda

   id     nombre  edad  salario       ciudad  salario_anual  edad_doble
0  11     Camila    25     2000  Bucaramanga          24000          50
1  12  CRISTHIAN    32     3000    Cartagena          36000          64
2  13       Juan    27     4000  Bucaramanga          48000          54
3  14      Betty    30     5000         Cali          60000          60

In [45]:
dfn = dfn.rename(columns= {'edad': 'age'}) #Renombrar columnas, entonces la columna edad la renombra como edad en inglés
dfn

   id     nombre  age  salario       ciudad  salario_anual  edad_doble
0  11     Camila   25     2000  Bucaramanga          24000          50
1  12  CRISTHIAN   32     3000    Cartagena          36000          64
2  13       Juan   27     4000  Bucaramanga          48000          54
3  14      Betty   30     5000         Cali          60000          60

In [59]:
dfn['nombre'] = dfn['nombre'].str.upper() #Convierte al objeto en letras mayúsculas como son las cadenas del nombre
dfn['nombre'] = dfn['nombre'].str.strip() #Limpia las cadenas del nombre y eliminando los espacios en blanco
dfn['nombre'] = dfn['nombre'].str.replace('JUAN', 'JOHAN') #Replace reemplaza a JUAN por JOHAN

In [60]:
dfn

   id     nombre  age  salario       ciudad  salario_anual  edad_doble
0  11     CAMILA   25     2000  Bucaramanga          24000          50
1  12  CRISTHIAN   32     3000    Cartagena          36000          64
2  13      JOHAN   27     4000  Bucaramanga          48000          54
3  14      BETTY   30     5000         Cali          60000          60

In [61]:
grupo = dfn.groupby('ciudad')['salario'].mean()
grupo
#Este método toma la columna ciudad y todos los elementos de la columna salario, para calcular la media aritmética del salario
#Agrupa todos los elementos de ciudad y calcula a esos grupos la media aritmética

ciudad
Bucaramanga    3000.0
Cali           5000.0
Cartagena      3000.0
Name: salario, dtype: float64

In [62]:
ordenado = dfn.sort_values(by= 'age')
ordenado
#Ordenar los datos de la base de datos

   id     nombre  age  salario       ciudad  salario_anual  edad_doble
0  11     CAMILA   25     2000  Bucaramanga          24000          50
2  13      JOHAN   27     4000  Bucaramanga          48000          54
3  14      BETTY   30     5000         Cali          60000          60
1  12  CRISTHIAN   32     3000    Cartagena          36000          64

In [65]:
dfn1 = pd.DataFrame({
    'id': [11, 12, 13, 14],
    'departamento': ['Ventas', 'IT', 'RRHH', 'Marketing']
    })

merge = pd.merge(dfn, dfn1, on= 'id')
merge

,id,nombre,age,salario,ciudad,salario_anual,edad_doble,departamento
0,11,CAMILA,25,2000,Bucaramanga,24000,50,Ventas
1,12,CRISTHIAN,32,3000,Cartagena,36000,64,IT
2,13,JOHAN,27,4000,Bucaramanga,48000,54,RRHH
3,14,BETTY,30,5000,Cali,60000,60,Marketing

In [66]:
valores = dfn.values
valores
#Sí se quiere cambiar un objeto tipo Pandas a un objeto tipo NumPy, usamos el método values

array([[11, 'CAMILA', 25, 2000, 'Bucaramanga', 24000, 50],
       [12, 'CRISTHIAN', 32, 3000, 'Cartagena', 36000, 64],
       [13, 'JOHAN', 27, 4000, 'Bucaramanga', 48000, 54],
       [14, 'BETTY', 30, 5000, 'Cali', 60000, 60]], dtype=object)

In [68]:
arr = np.array([11, 21, 31])
df = pd.DataFrame(arr)
df
#Sí se quiere cambiar un objeto tipo NumPy a un objeto tipo Pandas, usamos el método DataFrame

    0
0  11
1  21
2  31

**Último código incompleto por el video tutorial**

In [ ]:
import pandas as pd
import numpy as pd
from skearln.model_selection import train_test_split
from skearln.discriminant_analysis import LinearDiscriminantAnalysis

#--------------------------------
#1. CREACIÓN DEL DATAFRAME
#--------------------------------

#Simulación de datos (reemplaza esto con tus datos reales)
f_capitulos1 = pd.DataFrame({
    'F_04': [15, 16, 17, np.nan, 18],
    'F_09': [2, 4, 1, 3, np.nan],
    'F_10_A': [1, np.nan, 3, 2, 1],
    'F_19': [0, 1, 0, 1, 1]})

#Crear tabla_alcohol
tabla_alcohol = pd.DataFrame({
    'edad': f_capitulos1['F_04'],
    'borrachera': f_capitulos1['F_09'],
    'cerveza': f_capitulos1['F_10_A'],
    'alcohol': f_capitulos1['F_19']})

#--------------------------------
#2. PREPROCESAMIENTO DE DATOS
#--------------------------------

ModuleNotFoundError: No module named 'skearln'